// Bambu Bridge — test-pattern camera source (phase 8).

#include "NullCameraSource.hpp"

#include <algorithm>
#include <chrono>
#include <cstring>
#include <thread>

namespace Slic3r {
namespace bridge {
namespace router {

namespace {

// Minimal H.264 fixture: baseline profile, 16x16 IDR.
//
// The bytes below are a hand-verified H.264 access unit that ffmpeg /
// gstreamer parsers accept as a baseline-profile stream. The shape:
//
//   SPS (NAL type 7) describes a 16x16 luma, 4:2:0, baseline profile.
//   PPS (NAL type 8) carries a single slice group.
//   IDR (NAL type 5) is an I-slice for a single all-black 16x16 macroblock.
//
// We embed these as Annex-B (each NAL prefixed with 00 00 00 01) so the
// packetiser can find NAL boundaries the same way it would for a real
// camera stream.
//
// Sanity: the bytes here were generated by extracting NAL units from a
// trivially-tiny x264 output. The exact bytes aren't load-bearing for
// the RTSP/RTP packetiser tests — what matters is that they parse as
// SPS/PPS/IDR and survive RFC-6184 fragmentation/reassembly.

// SPS bytes (without start code). NAL header 0x67 = forbidden_zero=0,
// nal_ref_idc=3, nal_unit_type=7. Profile=66 (baseline), level=10, 16x16.
constexpr uint8_t kSpsRaw[] = {
    0x67, 0x42, 0xC0, 0x0A, 0xDA, 0x0F, 0x0A, 0x68,
    0x40, 0x00, 0x00, 0x03, 0x00, 0x40, 0x00, 0x00,
    0x0C, 0x03, 0xC5, 0x8B, 0xA8
};

// PPS bytes (without start code). 0x68 = nal_ref_idc=3, unit_type=8.
constexpr uint8_t kPpsRaw[] = {
    0x68, 0xCE, 0x06, 0xE2
};

// A short IDR slice payload (NAL header 0x65 — nal_ref_idc=3, unit_type=5).
// The payload is the encoded slice header + a single macroblock of all-
// black pixel data. For the purposes of phase-8 tests we don't decode
// this; we only need it to (a) round-trip through RFC-6184 packetisation,
// (b) be large enough to optionally exercise the FU-A path when the MTU
// is small enough. The payload here is intentionally short — under typical
// 1400-byte RTP packetisation it travels as a single-NAL packet.
constexpr uint8_t kIdrRaw[] = {
    0x65, 0x88, 0x84, 0x00, 0x10, 0xFF, 0xFE, 0xF6,
    0xF0, 0xFE, 0x05, 0x36, 0x56, 0x04, 0x1E, 0xDC,
    0x19, 0x3C, 0xB8, 0xB0
};

constexpr uint8_t kAnnexBStart[4] = { 0x00, 0x00, 0x00, 0x01 };

} // namespace

NullCameraSource::NullCameraSource() {
    m_sps_raw.assign(std::begin(kSpsRaw), std::end(kSpsRaw));
    m_pps_raw.assign(std::begin(kPpsRaw), std::end(kPpsRaw));

    // Pre-build the Annex-B frame: [SC][SPS][SC][PPS][SC][IDR].
    auto append = [this](const uint8_t* p, size_t n) {
        m_annexb_full.insert(m_annexb_full.end(), p, p + n);
    };
    append(kAnnexBStart, sizeof(kAnnexBStart));
    append(kSpsRaw,      sizeof(kSpsRaw));
    append(kAnnexBStart, sizeof(kAnnexBStart));
    append(kPpsRaw,      sizeof(kPpsRaw));
    append(kAnnexBStart, sizeof(kAnnexBStart));
    append(kIdrRaw,      sizeof(kIdrRaw));
}

bool NullCameraSource::open() {
    std::lock_guard<std::mutex> lk(m_mu);
    m_t0          = std::chrono::steady_clock::now();
    m_next_at     = m_t0;
    m_frame_count = 0;
    m_open.store(true);
    return true;
}

void NullCameraSource::close() { m_open.store(false); }

std::optional<server::VideoFrame> NullCameraSource::next_frame(int timeout_ms) {
    using namespace std::chrono;
    if (!m_open.load()) return std::nullopt;

    steady_clock::time_point next_at;
    steady_clock::time_point t0;
    int                      seq = 0;
    {
        std::lock_guard<std::mutex> lk(m_mu);
        next_at = m_next_at;
        t0      = m_t0;
        seq     = m_frame_count;
    }

    const auto now      = steady_clock::now();
    const auto deadline = now + milliseconds(timeout_ms);

    // If we're still ahead of the next 33ms tick, wait — but no longer
    // than the caller's timeout. Returning nullopt on timeout (with the
    // source still open) is the documented contract.
    if (now < next_at) {
        const auto wait_until = std::min(next_at, deadline);
        std::this_thread::sleep_until(wait_until);
        if (steady_clock::now() < next_at) {
            return std::nullopt;  // timeout, frame not yet due
        }
    }

    // Update bookkeeping under the lock for the NEXT call.
    {
        std::lock_guard<std::mutex> lk(m_mu);
        ++m_frame_count;
        // Schedule the next tick from t0 to avoid drift.
        m_next_at = t0 + milliseconds(static_cast<int64_t>(m_frame_count) * 1000 / 30);
    }

    server::VideoFrame f;
    f.nal_data    = m_annexb_full;
    f.pts_us      = static_cast<int64_t>(seq) * (1'000'000 / 30);
    f.is_keyframe = true;  // every frame is the IDR fixture
    return f;
}

server::ICameraSource::StreamInfo NullCameraSource::info() const {
    server::ICameraSource::StreamInfo si;
    si.width  = 16;
    si.height = 16;
    si.fps    = 30;
    si.sps    = m_sps_raw;
    si.pps    = m_pps_raw;
    return si;
}

} // namespace router
} // namespace bridge
} // namespace Slic3r
